# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: CatalystDevOrg.CatalystBrowser
PackageVersion: 3.9.4
PackageLocale: en-US
Publisher: CatalystDevOrg
PackageName: catalyst-browser
License: MIT License
Copyright: Copyright © 2024 CatalystDevOrg
ShortDescription: A minimal, functional, and customizable user-focused FOSS web browser
ManifestType: defaultLocale
ManifestVersion: 1.6.0
